name: Conmech Container Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: michaljur/conmech3d:latest
    steps:
      - name: Downloading code
        shell: bash
          rm -rf *
          git init
          url=${{ github.repositoryUrl }}
          git remote add origin ${url/git:/https:}
        run: |
          git pull origin ${{ github.sha }}
      - name: Running tests
        shell: bash
        run: pytest --ignore=tests/test_deep_conmech -p no:unraisableexception -s --verbose
