name: Deep Conmech Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: michaljur/deep_conmech:latest
    steps:
      - name: Downloading code
        shell: bash
        run: |
          git init
          url=${{ github.repositoryUrl }}
          git remote add origin ${url/git:/https:}
          git pull origin ${{ github.sha }}
      - name: Install requirements
        shell: bash
        run: |
          pip install -r requirements.txt
          pip install -r requirements-deep.txt
      - name: Running tests
        shell: bash
        run: PYTHONPATH=. pytest tests/test_deep_conmech -p no:unraisableexception
